src/app/globals.css, tailwind.config.js
tailwind config 추가
-
-
- close #
=> [DP-1] style: add tailwind.config

package-lock.json, package.json, src/app/(home)/page.tsx, src/components/common/modal/BaseModal.tsx, src/components/common/modal/ModalHeader.tsx, tailwind.config.js
[x] modal 공통 컴포넌트 구현
- 추후 custom 모달로 확장할 예정입니다.
- home 화면에서 테스트 진행했습니다.
- 기본 base modal입니다.
- header 없는 버전입니다.
- close #10
=> [DP-39] feat: 모달 컴포넌트 구현 #10

README.md
- README.md 작성
- 서비스 소개 (기획배경, 문제점/솔루션, 타겟층, 차별점, 요약)
- 디렉토리 구조
- 실행 방법
- 상세 기능 설명
- 팀원 소개, 역할 분담
- 멘토링 이후 리드미 수정할 예정
- close #52
=> [DP-67] docs: README.md 작성 #52

src/feature/mypage/apis/mypageRequest.ts, src/feature/mypage/components/sections/profile/CurrentCashCard.tsx
캐시 잔여량 조회기능
- 잔여량 조회 component api 연동
-
- close #
=> [DP-158] feat: add-get-user-info

src/feature/map/components/pages/MapDetailPage.tsx
- merge 픽스 했습니다.
-
- close #104
=> [DP-135] fix: merge myProduct #104

src/feature/mypage/components/pages/MyPageContent.tsx, src/feature/mypage/components/sections/profile/CicularProgressBar.tsx
현재 데이터 잔량 API 연동
-
-
- close #
=> [DP-202] feat: add current data value

src/components/common/AvatarIcon.tsx, src/feature/map/components/pages/MapPage.tsx, src/feature/map/components/sections/product/MapContainer.tsx, src/feature/map/components/sections/product/MapFloatingButtons.tsx, src/hooks/useMapHeight.ts
- 컴퓨터 화면에서 지도 중심이 잡히지 않는 것을 수정했습니다.
-
- close #185
=> [DP-230] feat: 컴퓨터 화면에서 중심 수정 #185

package-lock.json, package.json, src/app/layout.tsx
- vercel에 speed insight 를 위해 추가하였습니다.
-
- close #185
=> [DP-230] feat: speed insight 추가 #185

src/app/layout.tsx
- 사용자 행동 분석을 위한 Hotjar 추적 코드 추가
- `app/head.tsx`에 `dangerouslySetInnerHTML` 방식으로 삽입
- Site ID: 6480256
- 배포 후 https://dapanda.org 에서 스크립트가 정상 로드되는지 확인
- Hotjar Dashboard > Verify Installation 진행 예정
- close #239
=> [DP-239] feat: Hotjar 추적 스크립트 추가 및 설치 준비

src/feature/notification/api/postFcmToken.ts, src/feature/notification/api/requestNotification.ts, src/feature/notification/components/pages/NotificationPageContent.tsx, src/feature/notification/components/sections/NotificationCard.tsx, src/feature/notification/utils/requestFcmToken.ts
- 알림 서버 연동 준비 완료 (백엔드 API 개발 대기 상태)
- `fetchNotifications`, `deleteNotification` 함수 scaffold 작성
- `NotificationPageContent`에서 mock 데이터 유지하며, // TODO: 서버 연동 예정 주석 추가
- 서버 응답 형식에 맞춰 최소 타입 정의(`NotificationResponse`) 포함
- 알림카드 왼쪽으로 슬라이드 한 뒤 아무곳이나 클릭하면 제자리로 돌아오도록 구현
- 현재 FCM 알림이 오긴 함(백엔드 에러 있어서 수정할 예정)
- 백엔드에서 api 개발되면 주석 해제 후 연동 바로 가능
- UI 및 삭제 애니메이션은 기존과 동일
- close #176
=> [DP-224] feat: 알림 조회/삭제 API 연동 준비 #176

src/feature/map/hooks/useMapInitializer.ts, src/middleware.ts
-배포 환경에서 지도 탭 진입 시 fetch 추가 했습니다.
-
- close #
=> [DP-249] 배포 환경에서 지도 탭 진입 시 fetch 추가 #209

src/app/(feature)/mypage/charge/fail/page.tsx, src/app/(feature)/mypage/layout.tsx, src/app/error/page.tsx, src/app/not-found.tsx, src/components/common/modal/BaseModal.tsx, src/components/common/modal/FullScreenModal.tsx, src/feature/data/components/pages/DataDetailContent.tsx, src/feature/data/components/pages/DataPageContent.tsx, src/feature/data/components/pages/DefaultTabContent.tsx, src/feature/map/components/pages/MapSelectLocation.tsx, src/feature/map/components/sections/product/MapBottomSheet.tsx, src/feature/map/components/sections/product/MapContainer.tsx, src/feature/map/components/sections/regist/MapSelectedInfoCard.tsx, src/feature/mypage/components/pages/ChargeFailPageContent.tsx, src/feature/mypage/components/sections/charge/FailedMessage.tsx, src/feature/mypage/components/sections/profile/DataStateComponent.tsx, src/feature/mypage/components/sections/toss/TossPaymentModal.tsx, src/feature/payment/components/PaymentCompleteModal.tsx, src/feature/payment/components/PaymentConfirmModal.tsx, src/feature/payment/components/PaymentModal.tsx, src/middleware.ts
Layout 깨짐 수정
- max width 변경 side effect 수정
-
- close #
=> [DP-232] fix: data page mobile view

src/feature/data/components/sections/modal/DataRegistModal.tsx
- 데이터 게시글 등록할때 가격 입력 제한 추가 (0~10000000)
-
- close #
=> [DP-243] feat: 가격 제한 추가

src/app/(feature)/layout.tsx
=> [DP-260] fix: 탑시트 수정 #226

src/app/(feature)/layout.tsx, src/app/globals.css, src/feature/data/components/pages/DataDetailContent.tsx, src/feature/mypage/components/pages/ReviewPageContent.tsx
- 프로필 및 탑시트 레이아웃을 수정하였습니다
-
- close #226
=> [DP-260] fix: 프로필 및 탑시트 레이아웃 수정 #226

src/app/(feature)/map/regist/wifi/form/page.tsx
register page scroll 수정
-
-
- close #
=> [DP-232] fix: fix registerpage

src/feature/notification/components/pages/NotificationPageContent.tsx, src/feature/notification/components/sections/NotificationList.tsx
notification page scroll 수정
-
-
- close #
=> [DP-232] fix: fix notification page

src/app/(feature)/@modal/default.tsx, src/feature/chat/components/sections/room/ChatRoomContent.tsx, src/feature/data/components/pages/DataPageContent.tsx, src/feature/map/components/pages/MapSelectLocation.tsx
* [DP-232] fix: fix notification page
* [DP-232] fix: fix ui broken
* [DP-232] fix: fix globalcss
* [DP-232] fix: fix chatroom
* [DP-232] fix: add middleware
deploy를 위해 develop -> main 병합
-
-
- close #
[DP-232]: https://dapanda.atlassian.net/browse/DP-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DP-232]: https://dapanda.atlassian.net/browse/DP-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DP-232]: https://dapanda.atlassian.net/browse/DP-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DP-232]: https://dapanda.atlassian.net/browse/DP-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DP-232]: …
=> [MERGE] main 병합

src/components/common/bottomsheet/BaseBottomSheet.tsx
- 바텀시트 스크롤이 중첩되는 현상 수정하였습니다.
- 더미데이터로 테스트 해보았기 때문에 실제 배포 시 확인이 필요해보입니다.
https://github.com/user-attachments/assets/fa99074a-a700-4bcc-8112-b9e0ab41e0e6
- close #
=> [DP-260] refactor: 바텀시트 스크롤 중첩 수정 #226

src/app/globals.css, src/feature/chat/components/sections/room/ChatRoomContent.tsx
-모바일 키보드 노출 시 채팅 영역의 스크롤 동작 문제 해결 및 레이아웃 조정
- h-screen 추가로 전체 높이 고정
- 스크롤 숨김 처리 추가
- 키보드 활성 시 레이아웃 동적 계산 적용
=> [DP-259] fix: keyboard 스크롤 재반영 #225

src/components/common/ProviderWrapper.tsx, src/components/common/bottomsheet/BaseBottomSheet.tsx, src/stores/useWebSocketStore.ts
- pc 환경에서 바텀시트 드래그가 안 되는 부분 수정했습니다.
-
- close #
=> [DP-260] fix: pc 환경에서 드래그 불가 수정 #226

src/feature/mypage/components/pages/CashActionContent.tsx, src/feature/mypage/components/sections/toss/TossPaymentModal.tsx
=> [DP-291] feat: 토스모달 스크롤 추가 #280

src/feature/map/components/sections/product/MapBottomSheet.tsx, src/hooks/useAuth.ts
- useAuth 수정으로 웹소켓 연결되게 수정하였습니다.
- 위치정보 없을 시 디폴트 값 추가하였습니다. 
-
- close #
=> [DP-253] feat: 와이파이 타이머 추가 #215

src/feature/chat/components/sections/list/ChatList.tsx, src/feature/chat/components/sections/room/ChatPostCard.tsx, src/feature/chat/components/sections/room/ChatRoomContent.tsx, src/feature/chat/utils/productCache.ts
**채팅방 상단 PostCard에서 기본 데이터 이미지 대신,
실제 와이파이 상품에 등록된 첫 번째 이미지가 표시되도록 수정했습니다.**
- ChatPostCard 컴포넌트에 imageUrls props 추가
- ChatRoomContent에서 상품 데이터에 포함된 이미지 배열 전달
- productCache에서 imageUrls 필드를 포함하여 상품 정보 구성
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/5ae16668-1c64-45bd-852d-fd4cfa2a001a" width="300" /></td>
<td><img src="https://github.com/user-attachments/assets/565a3652-f399-4a68-92e9-db59af59fede" width="300" /></td>
</tr>
</table>
- close #327
=> [DP-325] feat: postcard 와이파이 첫 번째 이미지 받아오는걸로 구현

src/app/layout.tsx, src/components/common/AvatarIcon.tsx, src/components/common/ProviderWrapper.tsx, src/feature/chat/components/ChatContainer.tsx
- Hotjar 스크립트를 window.onload 이후로 지연 로딩하여 초기 렌더링 차단 제거
-  AvatarIcon에서 medium, large 아바타에 priority 옵션 적용 (LCP 대상 우선 렌더링)
- ProviderWrapper 내 채팅 데이터 로딩을 1초 지연 처리하여 렌더링 병목 개선
- close #325
=> [DP-324] refactor: 채팅 로딩 지연 처리 및 아바타 우선 렌더링 적용

src/app/api/auth/me/route.ts, src/components/common/FcmInitializer.tsx, src/feature/chat/components/ChatContainer.tsx, src/feature/chat/components/sections/list/ChatList.tsx, src/feature/data/api/dataRequest.ts, src/feature/data/components/pages/DataDetailContent.tsx, src/feature/data/components/sections/modal/DataRegistModal.tsx, src/feature/data/hooks/usePriceRecommendation.ts, src/feature/notification/utils/requestFcmToken.ts, src/hooks/useAuth.ts
=> [DP-335] fix: hotfix remove unfitted requests

src/feature/chat/components/ChatContainer.tsx
=> [DP-335] fix: fix dependency array
